### ISSUE TITLE
Error when looking for some complex patterns

### ISSUE THREAD

**Issue by lcheylus** [jhx0/pkgsearch#10]
For "complex" patterns with special characters (for example `g++`), pkgsearch crashes:

```bash
$ pkgsearch 'g++'
Search packages 'g++' for release 7.4 / arch amd64
Traceback (most recent call last):
  File "/home/fox/bin/pkgsearch", line 244, in <module>
    main()
  File "/home/fox/bin/pkgsearch", line 240, in main
    query_index(index_path, args.package, args.emoji)
  File "/home/fox/bin/pkgsearch", line 154, in query_index
    if re.findall(needle, pkg):
  File "/usr/local/lib/python3.10/re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/local/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.10/sre_parse.py", line 672, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 2
```

Need to do some debug with `re` module in `query_index` function.

**Comment by jhx0** [comment]
Sorry for the late reply.
I'm currently quite busy. Trying to take a look at it on the weekend if time permits.
First of all: Thanks for reporting the issue @lcheylus !

**Comment by jhx0** [comment]
I had a look into it.
So far I cannot reproduce the problem here locally.

```shell
[prometheus /mnt/nas/Private/Code/projects/pkgsearch] $ ./pkgsearch 'g\+\+'
Search packages 'g\+\+' for release 7.4 / arch amd64
g++-11.2.0p9                                              - Size: 26.34MB
g++-8.4.0p18                                              - Size: 25.60MB
[prometheus /mnt/nas/Private/Code/projects/pkgsearch] $ ./pkgsearch 'g++' | tail
zangband-2.6.2p6-no_x11                                   - Size: 1.32MB
zangband-2.6.2p6                                          - Size: 1.34MB
zh-libchewing-0.5.1p0                                     - Size: 2.01MB
zig-0.11.0p0                                              - Size: 70.56MB
zimg-3.0.4                                                - Size: 0.95MB
zint-gui-2.12.0                                           - Size: 1.67MB
zoidberg-0.981p0                                          - Size: 0.14MB
zsh-syntax-highlighting-0.7.1                             - Size: 0.04MB
zxing-20190320p3                                          - Size: 0.39MB
zxing-cpp-2.1.0                                           - Size: 0.69MB
```

Is this maybe specific to the Python install on your end? (Or the version/re module version?)

Tested it on Debian locally - There should be no difference normally.

**Comment by jhx0** [comment]
Were you able to reproduce the problem on your end currently @lcheylus ?

**Comment by lcheylus** [comment]
Hi @jhx0, time to close this bug after some tests.

I didn't understand that the `package` argument is a regexp to search packages in index file. I submitted [PR#14](https://github.com/jhx0/pkgsearch/pull/14) to add help for `package` parameter.
